server:
  port: 8080

application:
  security:
    jwt:
      secret-key: TU_CLAVE_SECRETA_AQUI
      expiration: 86400000 # 1 día en milisegundos
      refresh-token:
        expiration: 604800000 # 7 días en milisegundos

spring:
  application:
    name: SaborASelva
  datasource:
    url: jdbc:postgresql://localhost:5432/mybdss
    username: mybdss
    password: mybdss
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: data
        dialect: org.hibernate.dialect.PostgreSQLDialect




