spring:
  application:
    name: SaborASelva
  datasource:
    url: jdbc:postgresql://localhost:5432/mybdss
    username: mybdss
    password: mybdss
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: data
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# eureka:
#   instance:
#     instance-id: ${spring.application.name}:${random.value}
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka